apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - secret/mysql-secret.yaml
  - configmap/app-configmap.yaml
  - deployment/mysql-statefulset.yaml
  - deployment/app-deployment.yaml
  - service/services.yaml
  - ingress/ingress.yaml
  - hpa/app-hpa.yaml
